#!/usr/bin/env python3
"""
Generalized premium product-reel builder (config-driven).

Turns a folder of product images + a per-scene voiceover script into a polished
9:16 Instagram reel, in one or more languages, with:
  - a glowing brand logo (top, on a dark scrim so it reads on any image) and a
    persistent contact/address footer (bottom)
  - NO-CROP Ken-Burns zoom (each image is contained with head-room, so nothing on
    the edges is ever clipped while it zooms) + crossfade/slide transitions
  - per-language bottom subtitles (language-appropriate font)
  - Gemini TTS voiceover (per scene, retried, silence-trimmed) synced to each scene
  - an original, copyright-free, phone-audible ambient music bed, gently ducked
    under the voice.

Design decisions that matter for "average view duration":
  * Scene durations are computed PER LANGUAGE, so the English cut is never padded
    out to match a longer Hindi line (that was the main source of dead air).
  * Each TTS clip is silence-trimmed and scenes carry only a small tail, so there
    is very little gap between spoken lines.
  * The final scene gets an explicit tail so the closing line is never cut off.

Everything is data-driven via a JSON config (see config.example.json). To make a
reel for a NEW product you only change: the images, the `scenes` voiceover text,
the `voice`, and the `company` block.

Requires: ffmpeg (xfade/overlay/zoompan/sidechaincompress; drawtext NOT needed —
captions are Pillow-rendered), Pillow, google-genai, a Gemini API key.

Usage:  python build_reel.py config.json
"""
import hashlib
import json, math, os, subprocess, sys, time, wave
from PIL import Image, ImageDraw, ImageFont, ImageFilter
try:
    import numpy as _np
except ImportError:                              # the pad bed still works
    _np = None


VOLATILE_ROOTS = ("/tmp", "/var/tmp")            # wiped on reboot — never keep work here


def _resolve(base, p):
    """Make a configured path absolute relative to the CONFIG FILE's directory
    (NOT the process CWD), so the builder can be run from anywhere and still
    write next to the project. Already-absolute paths are left untouched."""
    p = os.path.expanduser(str(p))
    return p if os.path.isabs(p) else os.path.normpath(os.path.join(base, p))


def _warn_volatile(key, path):
    """Loud warning if a working/output dir lands in the system temp dir. We do
    NOT rewrite an explicit absolute choice — but /tmp is erased on reboot, which
    destroys the slow, TTS-quota-limited, resumable progress this builder keeps."""
    real = os.path.realpath(path)
    if any(real == r or real.startswith(r + os.sep) for r in VOLATILE_ROOTS):
        print(f"!! WARNING: \"{key}\" resolves to {real} (system temp dir).\n"
              f"!!   Files there are ERASED ON REBOOT / power loss — you would lose the resumable\n"
              f"!!   TTS clips, rendered scene clips and the final video, and burn Gemini TTS quota\n"
              f"!!   regenerating them. Use a PROJECT-LOCAL path instead, e.g. \"{key}\": "
              f"\"{'.reel_build' if key == 'tmp_dir' else 'promo'}\" (resolved next to the config file).",
              file=sys.stderr, flush=True)


def load_cfg(path):
    # Every path in the config is anchored to the config file's own directory, so
    # ALL working files (TTS wavs, stage/overlay PNGs, per-scene clips, music bed,
    # stitched video, final MP4/MKV) stay project-local and survive a reboot.
    cfg_path = os.path.abspath(os.path.expanduser(path))
    base = os.path.dirname(cfg_path)
    cfg = json.load(open(cfg_path))
    cfg["_cfg_path"], cfg["_cfg_dir"] = cfg_path, base
    if not cfg.get("gemini_key") and cfg.get("gemini_key_file"):
        cfg["gemini_key"] = open(_resolve(base, cfg["gemini_key_file"])).read().strip()
    if not cfg.get("openai_key") and cfg.get("openai_key_file"):
        cfg["openai_key"] = open(_resolve(base, cfg["openai_key_file"])).read().strip()
    # Provider selection is OPT-IN and purely additive: omit both keys and every existing
    # config (pixel, enhance, og, ...) keeps taking the exact Gemini path it always has.
    cfg.setdefault("tts_provider", "gemini")      # "gemini" | "openai"
    cfg.setdefault("image_provider", "gemini")    # informational; images are generated by a
                                                   # separate script, not by this builder
    cfg.setdefault("tmp_dir", ".tmp/reel_build")  # project-local (relative to the config)
    cfg.setdefault("voice", "Sulafat")           # warm female by default (Gemini voice name;
                                                  # use an OpenAI voice name when tts_provider
                                                  # is "openai", e.g. "onyx")
    if cfg["tts_provider"] == "openai":
        cfg.setdefault("tts_model", "gpt-4o-mini-tts")
    else:
        cfg.setdefault("tts_model", "gemini-2.5-flash-preview-tts")
    cfg.setdefault("tts_instructions", "")        # OpenAI-only: delivery/style direction passed
                                                   # to gpt-4o-mini-tts's "instructions" field.
                                                   # Empty = provider default delivery (no-op for
                                                   # Gemini, which has no such parameter).
    cfg.setdefault("fps", 30)
    cfg.setdefault("bg", "0x0d1117")
    cfg.setdefault("accent", (34, 211, 238))      # cyan
    cfg.setdefault("music", None)                 # None -> generate ambient bed
    cfg.setdefault("music_volume", 0.85)          # bed level (ducked further under VO)
    # Sidechain ducking strength (music vs VO). Defaults are the values this builder has
    # always used, so any config that doesn't set these keeps its exact old mix.
    cfg.setdefault("duck_threshold", 0.055)
    cfg.setdefault("duck_ratio", 3)
    cfg.setdefault("duck_attack", 25)
    # 420 ms was a film release: the bed crept back so slowly that the space
    # between two lines stayed quiet AND flat, which is the other half of why a
    # cut with no measurable silence still gets reported as full of it. At
    # 170 ms the beat is back before the next line starts, so the gap carries
    # the track instead of waiting for it.
    cfg.setdefault("duck_release", 170)
    cfg.setdefault("vo_loudnorm_i", None)         # e.g. -16: loudnorm the VO stem alone before
                                                   # mixing with music, so it reliably dominates.
                                                   # None (default) = no VO-only normalization,
                                                   # i.e. exactly today's behaviour.
    # ---------------------------------------------------------------- pacing
    #
    # These were all tuned for a calm product film and they made REELS that
    # died on the vine. Measured on a 13-scene cut with the old values: 12% of
    # the running time was silence, arriving as a ~0.7 s hole between every
    # single line (0.32 vo_pad + 0.5 s dissolve). A viewer reads that as the
    # video buffering, and buffering is a scroll.
    #
    # A reel is not a film. The eye is already moving; anything that waits gets
    # left behind. Every default below is now set for a feed, and every one of
    # them is still a knob — a project that genuinely wants the calm cut sets
    # "pace": "calm" and gets the old numbers back exactly.
    PACE = {
        "reel":  dict(vo_pad=0.10, vo_offset=0.08, vo_min_gap=0.06, min_scene=1.1,
                      last_tail=0.85, maxzoom=1.16, max_hold=2.6, xfade=0.12),
        "calm":  dict(vo_pad=0.32, vo_offset=0.14, vo_min_gap=0.25, min_scene=1.9,
                      last_tail=1.3, maxzoom=1.06, max_hold=99.0, xfade=0.5),
    }
    pace = PACE.get(cfg.setdefault("pace", "reel"), PACE["reel"])
    for k, v in pace.items():
        cfg.setdefault(k, v)

    cfg.setdefault("zoom_ss", 2)                  # supersample factor — kills zoompan jitter/shake
    # How long one still may hold before the builder cuts it into its own
    # sub-shots. A static frame is dead air with pictures on it: past about
    # two and a half seconds the viewer has finished reading it and is looking
    # for the next thing. See _plan_stills().
    cfg.setdefault("max_hold", 2.6)
    cfg.setdefault("logo_w", 430)
    cfg.setdefault("logo_glow", (120, 225, 255))  # cyan-white halo
    for k in ("tmp_dir", "out_dir", "images_dir"):
        if cfg.get(k):
            cfg[k] = _resolve(base, cfg[k])
    for k in ("tmp_dir", "out_dir"):
        _warn_volatile(k, cfg[k])
    os.makedirs(cfg["tmp_dir"], exist_ok=True)
    os.makedirs(cfg["out_dir"], exist_ok=True)
    return cfg


def _content_key(*parts):
    """Short stable key of the given parts — used to name cached artifacts so a
    change in any input (text, voice, image bytes, duration...) yields a new
    filename and an automatic, surgical re-generation of just that artifact."""
    h = hashlib.sha1()
    for p in parts:
        h.update(str(p).encode()); h.update(b"\x00")
    return h.hexdigest()[:12]


def _file_key(path):
    try:
        h = hashlib.sha1()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(1 << 16), b""):
                h.update(chunk)
        return h.hexdigest()[:12]
    except (OSError, TypeError):
        return "missing"


def _trim_silence(path):
    """Strip leading and trailing silence so lines butt up tightly.

    The Gemini path has always done this inline. Nothing else did — so a clip
    that arrived any OTHER way (the OpenAI provider, or one dropped in
    pre-rendered under the legacy name) kept whatever head and tail its
    synthesiser felt like adding. That silence is then paid TWICE: once as the
    hole you hear, and again as scene length, because every scene is timed to
    its own voiceover. Trim once, where a clip enters the cache, whoever made
    it."""
    t = path + ".trim.wav"
    af = ("silenceremove=start_periods=1:start_threshold=-40dB:start_silence=0.03:detection=peak,"
          "areverse,"
          "silenceremove=start_periods=1:start_threshold=-40dB:start_silence=0.05:detection=peak,"
          "areverse")
    r = subprocess.run(["ffmpeg", "-y", "-i", path, "-af", af, t], capture_output=True)
    if r.returncode == 0 and os.path.exists(t) and os.path.getsize(t) > 1000:
        os.replace(t, path)
    elif os.path.exists(t):
        os.remove(t)


def _adopt_legacy(legacy, hashed):
    """One-time migration: adopt a pre-hash cache file for the current inputs.

    Adopted clips are TRIMMED on the way in. A pre-rendered voiceover is the one
    kind the builder never spoke itself, so it is also the one kind whose
    silence nothing had ever taken off."""
    if not os.path.exists(hashed) and os.path.exists(legacy):
        os.replace(legacy, hashed)
        _trim_silence(hashed)


def _rgb(hexish):
    h = str(hexish).replace("0x", "").replace("#", "")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


# ---------------------------------------------------------------- TTS (dispatch)
def gen_tts(cfg):
    """Dispatch to the configured TTS provider. Default ("gemini") is byte-for-byte the
    original behaviour; "openai" is an additive alternate path (see gen_tts_openai)."""
    if cfg.get("tts_provider") == "openai":
        return gen_tts_openai(cfg)
    return gen_tts_gemini(cfg)


# ---------------------------------------------------------------- TTS (Gemini, default)
def gen_tts_gemini(cfg):
    from google import genai
    from google.genai import types
    client = genai.Client(api_key=cfg["gemini_key"])
    langs = list(cfg["languages"].keys())
    dur = {l: [] for l in langs}

    def trim(path):
        # strip leading/trailing silence so lines butt up tightly
        t = path + ".trim.wav"
        af = ("silenceremove=start_periods=1:start_threshold=-40dB:start_silence=0.03:detection=peak,"
              "areverse,"
              "silenceremove=start_periods=1:start_threshold=-40dB:start_silence=0.05:detection=peak,"
              "areverse")
        r = subprocess.run(["ffmpeg", "-y", "-i", path, "-af", af, t], capture_output=True)
        if r.returncode == 0 and os.path.exists(t) and os.path.getsize(t) > 1000:
            os.replace(t, path)

    quota_dead = [False]

    def valid(path):
        try:
            with wave.open(path) as w:
                n = w.getnframes(); return n / w.getframerate() if n else 0.0
        except Exception:
            return 0.0

    def one(text, out):
        d = valid(out)
        if d > 0.3:
            return d, False                       # reuse a clip we already generated
        if quota_dead[0]:
            return None, False
        text = text.replace("—", ", ").replace("·", " ").strip()
        for _ in range(6):
            try:
                r = client.models.generate_content(
                    model=cfg["tts_model"], contents=text,
                    config=types.GenerateContentConfig(
                        response_modalities=["AUDIO"],
                        speech_config=types.SpeechConfig(voice_config=types.VoiceConfig(
                            prebuilt_voice_config=types.PrebuiltVoiceConfig(voice_name=cfg["voice"])))))
                c = r.candidates[0] if r.candidates else None
                if c and c.content and c.content.parts and c.content.parts[0].inline_data \
                        and c.content.parts[0].inline_data.data:
                    with wave.open(out, "wb") as w:
                        w.setnchannels(1); w.setsampwidth(2); w.setframerate(24000)
                        w.writeframes(c.content.parts[0].inline_data.data)
                    trim(out); return valid(out), True
                time.sleep(3)                     # empty response — retry
            except Exception as e:
                s = str(e)
                if "per_day" in s or "PerDay" in s or "_per_day" in s:
                    quota_dead[0] = True          # daily cap hit; resets in hours, don't hammer it
                    return None, False
                time.sleep(8)                     # transient / per-minute — back off
        return None, False

    for l in langs:
        for i, sc in enumerate(cfg["scenes"]):
            key = _content_key("tts1", "gemini", cfg["tts_model"], cfg["voice"], sc["vo"][l])
            out = f"{cfg['tmp_dir']}/{l}{i}_{key}.wav"
            _adopt_legacy(f"{cfg['tmp_dir']}/{l}{i}.wav", out)
            cfg.setdefault("_wav", {}).setdefault(l, {})[i] = out
            d, called = one(sc["vo"][l], out)
            dur[l].append(d)
            src = "gen" if called else "cached"
            print(f"  tts {l}{i}: {'MISSING(quota)' if d is None else f'{d:.1f}s ({src})'}", flush=True)
            if called:
                time.sleep(cfg.get("tts_throttle", 6.0))   # stay under the per-minute limit

    complete = [l for l in langs if all(x is not None for x in dur[l])]
    cfg["_build_langs"] = complete
    missing = [l for l in langs if l not in complete]
    if missing:
        print(f"!! deferred (TTS daily quota): {missing}; building only {complete}", flush=True)
    return dur


# ---------------------------------------------------------------- TTS (OpenAI, opt-in)
def gen_tts_openai(cfg):
    """Alternate TTS path used only when config sets "tts_provider": "openai". Writes the
    exact same <tmp_dir>/{lang}{i}.wav layout as the Gemini path, so the rest of the
    pipeline (timings/build/mux) and the resumability logic are untouched.

    Quirk: the OpenAI /v1/audio/speech endpoint streams "wav" with a placeholder/invalid
    RIFF size in the header (Python's wave module reports a bogus giant nframes). The
    existing trim() step re-muxes the file through ffmpeg unconditionally, which also
    fixes the header as a side effect — so duration reads correctly afterwards. Do not
    skip trim() for this provider even if silence-trimming alone were unnecessary."""
    import urllib.request, urllib.error
    client = None
    try:
        from openai import OpenAI
        client = OpenAI(api_key=cfg["openai_key"])
    except Exception:
        client = None  # fall back to raw HTTP below if the SDK isn't installed
    langs = list(cfg["languages"].keys())
    dur = {l: [] for l in langs}

    def trim(path):
        t = path + ".trim.wav"
        af = ("silenceremove=start_periods=1:start_threshold=-40dB:start_silence=0.03:detection=peak,"
              "areverse,"
              "silenceremove=start_periods=1:start_threshold=-40dB:start_silence=0.05:detection=peak,"
              "areverse")
        r = subprocess.run(["ffmpeg", "-y", "-i", path, "-af", af, t], capture_output=True)
        if r.returncode == 0 and os.path.exists(t) and os.path.getsize(t) > 1000:
            os.replace(t, path)

    def valid(path):
        try:
            with wave.open(path) as w:
                n = w.getnframes(); return n / w.getframerate() if n else 0.0
        except Exception:
            return 0.0

    fatal = [False]

    def fetch(text):
        """Return raw wav bytes or raise. Uses the openai SDK if available, else urllib."""
        params = {"model": cfg["tts_model"], "input": text, "voice": cfg["voice"],
                  "response_format": "wav"}
        if cfg.get("tts_instructions"):
            params["instructions"] = cfg["tts_instructions"]
        if client is not None:
            resp = client.audio.speech.create(**params)
            return resp.read() if hasattr(resp, "read") else bytes(resp.content)
        body = json.dumps(params).encode()
        req = urllib.request.Request(
            "https://api.openai.com/v1/audio/speech", data=body, method="POST",
            headers={"Authorization": f"Bearer {cfg['openai_key']}", "Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=90) as resp:
            return resp.read()

    def one(text, out):
        d = valid(out)
        if d > 0.3:
            return d, False                       # reuse a clip we already generated
        if fatal[0]:
            return None, False
        text = text.replace("—", ", ").replace("·", " ").strip()
        for _ in range(6):
            try:
                data = fetch(text)
                if data:
                    with open(out, "wb") as fh:
                        fh.write(data)
                    trim(out); return valid(out), True
                time.sleep(3)                      # empty response — retry
            except urllib.error.HTTPError as e:
                if e.code in (401, 403):
                    fatal[0] = True                # bad/rejected key — don't hammer it
                    return None, False
                time.sleep(8)
            except Exception as e:
                s = str(e)
                if "invalid_api_key" in s or "AuthenticationError" in s:
                    fatal[0] = True
                    return None, False
                time.sleep(8)                      # transient / rate-limit — back off
        return None, False

    for l in langs:
        for i, sc in enumerate(cfg["scenes"]):
            key = _content_key("tts1", "openai", cfg.get("tts_model", ""), cfg["voice"], sc["vo"][l])
            out = f"{cfg['tmp_dir']}/{l}{i}_{key}.wav"
            _adopt_legacy(f"{cfg['tmp_dir']}/{l}{i}.wav", out)
            cfg.setdefault("_wav", {}).setdefault(l, {})[i] = out
            d, called = one(sc["vo"][l], out)
            dur[l].append(d)
            print(f"  tts {l}{i}: {'MISSING' if d is None else f'{d:.1f}s'}", flush=True)
            if called:
                time.sleep(cfg.get("tts_throttle", 1.0))

    complete = [l for l in langs if all(x is not None for x in dur[l])]
    cfg["_build_langs"] = complete
    missing = [l for l in langs if l not in complete]
    if missing:
        print(f"!! incomplete (openai TTS): {missing}; building only {complete}", flush=True)
    return dur


# ---------------------------------------------------------------- music bed
def make_music(cfg, seconds):
    if cfg["music"]:
        return cfg["music"]
    out = f"{cfg['tmp_dir']}/music_{int(seconds)}.wav"
    if os.path.exists(out) and os.path.getsize(out) > 1000:
        print("  music: cached", flush=True)
        return out
    # A bed with a PULSE, not a drone.
    #
    # This used to be seven sustained sine tones under a slow tremolo — a pad.
    # A pad is the correct bed for a product film and the wrong one for a reel,
    # and the symptom is oddly specific: the cut gets reported as "too much
    # silence between the lines" when measurement shows the voice track has no
    # silence in it at all. What is missing is not sound, it is EVENTS. With a
    # drone, nothing happens between one line and the next, so the gap plays as
    # dead air. Give the bed a beat and the same gap becomes momentum — the
    # thing people mean when they say a reel carries them.
    #
    # So: a four-on-the-floor pulse, an off-beat tick, a bass that moves every
    # bar, and a quiet pad for body — with the whole thing getting denser as it
    # runs, so the end feels like arrival rather than just the end. Synthesised
    # here, which means it is 100% original and cleared for paid ads; third
    # party "free" tracks almost always want attribution and are not.
    if _np is not None:
        try:
            return _synth_bed(cfg, out, seconds)
        except Exception as exc:                   # never fail a build over music
            print(f"  music: synth failed ({exc}); falling back to the pad", flush=True)

    freqs = [220, 261.63, 329.63, 392.0, 440.0, 523.25, 659.25]
    inp = []
    for f in freqs:
        inp += ["-f", "lavfi", "-i", f"sine=frequency={f}:duration={seconds}"]
    mix = "".join(f"[{i}]" for i in range(len(freqs)))
    fc = (f"{mix}amix=inputs={len(freqs)}:normalize=1,"
          f"tremolo=f=0.12:d=0.35,vibrato=f=0.1:d=0.25,"
          f"aecho=0.8:0.85:60|110:0.35|0.25,"
          f"highpass=f=150,lowpass=f=3600,"
          f"afade=t=in:st=0:d=2.5,afade=t=out:st={seconds - 3}:d=3,"
          f"loudnorm=I=-20:TP=-2:LRA=11,volume=1.0[a]")
    subprocess.run(["ffmpeg", "-y"] + inp + ["-filter_complex", fc, "-map", "[a]",
                    "-t", str(seconds), "-c:a", "pcm_s16le", out], check=True, capture_output=True)
    return out


# ---------------------------------------------------------------- music synth
def _synth_bed(cfg, out, seconds, sr=44100):
    """A driving, original bed: pulse + off-beat tick + moving bass + pad.

    Written with numpy rather than an ffmpeg filtergraph because the thing that
    makes a reel carry — a beat that arrives ON TIME, every time, and a
    density that builds — is a sequencer problem, and expressing a sequencer as
    a chain of `sine=` inputs is how you end up with a drone instead.

    Everything is generated from first principles, so the result is original
    and cleared for paid advertising. Third-party "royalty free" tracks almost
    always require attribution and are not cleared for ads.
    """
    bpm = float(cfg.get("music_bpm", 104))
    beat = 60.0 / bpm
    n = int(seconds * sr)
    t = _np.arange(n) / sr
    mix = _np.zeros(n, dtype=_np.float64)

    def place(buf, start_s, wave):
        i = int(start_s * sr)
        if i >= n:
            return
        k = min(len(wave), n - i)
        buf[i:i + k] += wave[:k]

    def env(length_s, attack=0.002, decay=None):
        m = int(length_s * sr)
        e = _np.ones(m)
        a = max(1, int(attack * sr))
        e[:a] = _np.linspace(0, 1, a)
        d = decay if decay is not None else length_s
        e *= _np.exp(-_np.arange(m) / (d * sr))
        return e

    # A minor, because it is the key the old pad was in and it suits a dark
    # brand palette. One chord change per four bars keeps it moving without
    # ever pulling focus from the voice.
    roots = [110.00, 146.83, 130.81, 164.81]        # A2  D3  C3  E3
    bars = max(1, int(seconds / (beat * 4)) + 1)

    for b in range(bars):
        bar_t = b * beat * 4
        root = roots[(b // 4) % len(roots)]
        # how far through the reel this bar is — the bed thickens as it goes
        grow = min(1.0, 0.45 + 0.55 * (bar_t / max(1.0, seconds)))

        for k in range(4):
            bt = bar_t + k * beat
            if bt > seconds:
                break
            # kick: a short pitch-dropping sine. Mid-low, because a phone
            # speaker cannot reproduce the sub-100 Hz where a real kick lives.
            m = int(0.15 * sr)
            f = 150 * _np.exp(-_np.arange(m) / (0.035 * sr)) + 72
            ph = _np.cumsum(2 * _np.pi * f / sr)
            place(mix, bt, _np.sin(ph) * env(0.15, 0.001, 0.055) * 0.55 * grow)

            # off-beat tick: filtered noise, the thing that actually creates
            # the sense of forward motion between the kicks.
            if b > 1:
                mnz = int(0.06 * sr)
                nz = _np.random.default_rng(b * 4 + k).standard_normal(mnz)
                nz = _np.convolve(nz, _np.array([1.0, -0.92]), mode="same")
                place(mix, bt + beat * 0.5, nz * env(0.06, 0.001, 0.018) * 0.10 * grow)

            # bass: one note per beat, root and fifth alternating
            bf = root if k % 2 == 0 else root * 1.5
            m = int(beat * 0.92 * sr)
            bw = _np.sin(2 * _np.pi * bf * _np.arange(m) / sr)
            bw += 0.3 * _np.sin(2 * _np.pi * bf * 2 * _np.arange(m) / sr)
            place(mix, bt, bw * env(beat * 0.92, 0.006, beat * 0.30) * 0.26 * grow)

    # pad: quiet, wide, just enough to stop the gaps sounding like a drum
    # machine in an empty room.
    for f in (220.0, 329.63, 440.0):
        mix += _np.sin(2 * _np.pi * f * t + _np.sin(2 * _np.pi * 0.08 * t)) * 0.035

    # tops and tails
    fade = int(0.6 * sr)
    mix[:fade] *= _np.linspace(0, 1, fade)
    tail = int(min(2.2, seconds * 0.1) * sr)
    mix[-tail:] *= _np.linspace(1, 0, tail)

    peak = float(_np.max(_np.abs(mix))) or 1.0
    pcm = (mix / peak * 0.82 * 32767).astype("<i2")
    with wave.open(out, "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(sr)
        w.writeframes(pcm.tobytes())
    print(f"  music: synthesised {seconds:.0f}s bed at {bpm:g} BPM", flush=True)
    return out


# ---------------------------------------------------------------- logo assets
def white_logo(cfg):
    src = cfg["company"].get("logo")
    if not src or not os.path.exists(src):
        return None
    out = f"{cfg['tmp_dir']}/logo_white.png"
    im = Image.open(src).convert("RGBA")
    alpha = im.split()[3]
    lo, hi = alpha.getextrema()
    if lo == hi:
        # asset has no real transparency (opaque bg): key out the light bg, ink -> white
        px = im.load(); w, h = im.size
        o = Image.new("RGBA", (w, h), (0, 0, 0, 0)); op = o.load()
        for y in range(h):
            for x in range(w):
                r, g, b, a = px[x, y]
                lum = (r * 299 + g * 587 + b * 114) // 1000
                op[x, y] = (255, 255, 255, 255 if lum < 180 else 0)
        o.save(out); return out
    # asset already carries a clean alpha shape: fill it SOLID white (bold + crisp)
    # and thicken strokes a touch so the wordmark reads strongly over any image.
    alpha = alpha.filter(ImageFilter.MaxFilter(3))
    o = Image.new("RGBA", im.size, (255, 255, 255, 0)); o.putalpha(alpha)
    o.save(out); return out


def build_logo(cfg):
    """Return (base_logo, glow) — white wordmark + a soft cyan halo, both padded."""
    wl = white_logo(cfg)
    if not wl:
        return None, None
    im = Image.open(wl).convert("RGBA")
    lw = cfg["logo_w"]; im = im.resize((lw, max(1, int(lw * im.height / im.width))), Image.LANCZOS)
    pad = 74
    cw, ch = im.width + 2 * pad, im.height + 2 * pad
    base = Image.new("RGBA", (cw, ch), (0, 0, 0, 0)); base.paste(im, (pad, pad), im)
    mask = base.split()[3].filter(ImageFilter.GaussianBlur(17))
    glow = Image.new("RGBA", (cw, ch), tuple(cfg["logo_glow"]) + (0,)); glow.putalpha(mask)
    return base, glow


def build_scrim(w, h=250):
    s = Image.new("RGBA", (w, h), (0, 0, 0, 0)); d = ImageDraw.Draw(s)
    for y in range(h):
        d.line([(0, y), (w, y)], fill=(6, 9, 14, int(150 * (1 - y / h) ** 1.4)))
    return s


def contain(im, bw, bh):
    r = min(bw / im.width, bh / im.height)
    return im.resize((max(1, int(im.width * r)), max(1, int(im.height * r))), Image.LANCZOS)


# ---------------------------------------------------------------- text wrap
def wrap(draw, text, font, maxw):
    words, lines, cur = text.split(), [], ""
    for wd in words:
        t = (cur + " " + wd).strip()
        if draw.textlength(t, font=font) <= maxw or not cur:
            cur = t
        else:
            lines.append(cur); cur = wd
    if cur:
        lines.append(cur)
    return lines


def _srt_t(sec):
    ms = int(round(max(0.0, sec) * 1000))
    h, ms = divmod(ms, 3600000); m, ms = divmod(ms, 60000); s, ms = divmod(ms, 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


#: Where each shot drifts, as a fraction of the head-room the zoom opens up.
#: A pure centred zoom is the thing people mean by "it looks like a slideshow":
#: nothing in the frame CHANGES RELATIVE to anything else, so the eye reads it
#: as a still that is slowly getting bigger. A drift across the frame is what
#: makes it read as a camera move — and cycling the direction shot to shot is
#: what stops six moves in a row feeling like one long one.
PANS = [
    (0.0, -1.0),   # push up
    (1.0, 0.0),    # track right
    (0.0, 1.0),    # push down
    (-1.0, 0.0),   # track left
    (0.7, -0.7),   # up and right
    (-0.7, 0.7),   # down and left
]


def _kenburns_fc(cfg, dur_s, z, SW, SH, SX, SY, W, H, FPS, pan=(0.0, 0.0)):
    """Ken-Burns clip filter. The stage PNG is rendered at cfg['zoom_ss']x
    resolution while zoompan outputs at display size (SWxSH): the per-frame x/y
    integer rounding lands in the big source space, so it is sub-pixel after the
    implicit downscale — no visible jitter/shake — at display-size render cost.

    `pan` is a unit direction the shot drifts in over its length. It is applied
    inside the head-room the zoom has already opened, so the frame never runs
    off the edge of the stage however long the shot is: at zoom z the visible
    window is iw/z wide, leaving (iw - iw/z) of slack, and the drift uses at
    most half of that either side of centre."""
    px, py = pan
    # 'on' is the output frame index; normalise it to 0..1 over the shot.
    n = max(1.0, dur_s * FPS - 1)
    tx = f"(on/{n:.3f})*2-1"                       # -1 .. +1 across the shot
    x = (f"iw/2-(iw/zoom/2)+({px:.3f})*({tx})*(iw-iw/zoom)/2" if px else
         "iw/2-(iw/zoom/2)")
    y = (f"ih/2-(ih/zoom/2)+({py:.3f})*({tx})*(ih-ih/zoom)/2" if py else
         "ih/2-(ih/zoom/2)")
    return (f"color=c={cfg['bg']}:s={W}x{H}:d={dur_s}:r={FPS}[bg];"
            f"[0:v]zoompan=z='{z}':x='{x}':y='{y}':"
            f"d=1:s={SW}x{SH}:fps={FPS}[zi];"
            f"[bg][zi]overlay={SX}:{SY}[bi];[bi][1:v]overlay=0:0[out]")


def transition(i, n, cfg=None):
    """How scene i arrives.

    Was: half-second dissolves nearly everywhere. Two problems with that in a
    feed. A long dissolve is a pause you cannot skip — it reads as the video
    buffering, and it is paid on EVERY cut, so on a 13-scene reel it quietly
    spends six seconds doing nothing. And a dissolve says "time passed", which
    is the wrong sentence between two lines of one argument; a CUT says "and
    another thing", which is the right one.

    So: cut by default (a 0.12 s dissolve — xfade needs a non-zero duration and
    at 0.12 it lands as a cut), with real moves saved for the two places a reel
    earns them: the turn out of the hook, and the closing card.
    """
    td = (cfg or {}).get("xfade", 0.12)
    if i == 1:
        return ("fade", min(0.30, td * 2.5))       # the hook releasing into the product
    if i == n - 1:
        return ("slideup", min(0.28, td * 2.2))    # the CTA arriving, not fading in
    if i % 4 == 0:
        return ("slideleft", td)                   # a beat every fourth cut, so it has rhythm
    return ("dissolve", td)


def _schedule(cfg, N, vlen):
    """Compute (sd, starts, total): per-scene VIDEO durations, VO start times (both in
    the final compressed timeline), and total length. `vlen[i]` is the measured TTS
    clip duration for scene i.

    BUGFIX (was shared, buggy, in two copies — timings() and master()): xfade
    compresses the video timeline by the transition duration `td` at every cut. The
    old code shifted each VO start back by that same `td` and only re-added the small
    `vo_offset`, so whenever `vo_pad + vo_offset < td` (true even for this builder's
    own defaults: 0.32 + 0.14 = 0.46 < the 0.5s default dissolve), line i+1 could start
    before line i finished speaking — audible overlap. This clamps every start to a
    real minimum gap (`vo_min_gap`) after the previous line ends, and — instead of
    just papering over it with a bigger pad that would break again at some other
    transition length — GROWS (never shrinks) the scene's own duration so the visual
    keeps covering the now-later audio, then recomputes the running timeline position
    from that actual duration so later xfade offsets stay consistent."""
    sd = []
    for i in range(N):
        v = vlen[i]
        d = (v + cfg["vo_offset"] + cfg["last_tail"]) if i == N - 1 \
            else max(v + cfg["vo_pad"], cfg["min_scene"])
        sd.append(round(d, 2))
    min_gap = cfg["vo_min_gap"]
    starts, acc = [round(cfg["vo_offset"], 3)], sd[0]
    for i in range(1, N):
        _, td = transition(i, N, cfg)
        appear = acc - td                          # when scene i visually appears (xfade offset)
        start = appear + cfg["vo_offset"]
        prev_end = starts[i - 1] + vlen[i - 1] + min_gap
        if start < prev_end:
            start = prev_end                        # clamp: never start before the prior line + gap
        start = round(start, 3)
        starts.append(start)
        vo_end = start + vlen[i]
        needed = round(vo_end - appear + cfg["vo_pad"], 2)
        if needed > sd[i]:
            sd[i] = needed                          # grow (never shrink) so video covers the audio
        acc = appear + sd[i]
    return sd, starts, round(acc, 3)


# ---------------------------------------------------------------- build
def build(cfg, dur):
    W, H, FPS = 1080, 1920, cfg["fps"]
    STAGE_W, STAGE_H, STAGE_X, STAGE_Y = 1080, 1000, 0, 200
    MZ = cfg["maxzoom"]
    BGRGB = _rgb(cfg["bg"])
    ACC = tuple(cfg["accent"]); WHITE = (255, 255, 255, 255); GREY = (150, 160, 172, 255)
    N = len(cfg["scenes"])
    FEN = cfg["languages"]
    base_logo, glow = build_logo(cfg)
    scrim = build_scrim(W)

    # ---- language-independent Ken-Burns "stage": rendered at zoom_ss x
    # resolution. Hi-res source => jitter-free zoompan.
    #
    # HEAD-ROOM IS NOT THE ZOOM. It used to be: the picture was shrunk by 1/
    # maxzoom so that even at full zoom nothing was ever cropped. That is a
    # sound guarantee and it has a nasty property — raising the zoom to make the
    # reel feel alive SHRINKS THE PICTURE. Going from 1.06 to 1.16 quietly took
    # fourteen percent off every frame, on the format where screen area is
    # scarcest, to protect against a crop that happens only at the very end of a
    # move and that nobody has ever noticed in a Ken-Burns shot.
    #
    # So they are two knobs now. The stage is built with `zoom_headroom` (a
    # little slack, default 1.06) and `maxzoom` is free to be as lively as the
    # cut needs; past the head-room a move crops slightly into the picture at
    # its extreme, which is what a camera push does.
    SS = cfg["zoom_ss"]; SGW, SGH = STAGE_W * SS, STAGE_H * SS
    HR = max(1.0, float(cfg.get("zoom_headroom", 1.06)))
    inner_w, inner_h = int(SGW / HR) - 8 * SS, int(SGH / HR) - 8 * SS
    # A scene's "image" may be a single filename OR a list of filenames: with a
    # list, the scene cuts between the images (equal splits, each with its own
    # Ken-Burns) so no visual holds longer than a few seconds — better retention.
    def scene_images(sc):
        im = sc["image"]
        return list(im) if isinstance(im, (list, tuple)) else [im]

    _stage_cache = {}

    def stage_for(img):
        if img not in _stage_cache:
            p = f"{cfg['tmp_dir']}/stage_{_content_key('stage1', img, _file_key(os.path.join(cfg['images_dir'], img)), SS, HR)}.png"
            if not os.path.exists(p):
                prod = Image.open(os.path.join(cfg["images_dir"], img)).convert("RGBA")
                prod = contain(prod, inner_w, inner_h)
                st = Image.new("RGB", (SGW, SGH), BGRGB)
                st.paste(prod, ((SGW - prod.width) // 2, (SGH - prod.height) // 2), prod)
                st.save(p)
            _stage_cache[img] = p
        return _stage_cache[img]

    stage = [[stage_for(im) for im in scene_images(sc)] for sc in cfg["scenes"]]

    def timings(lang):
        return _schedule(cfg, N, dur[lang])

    def overlay(text, lang, gi, path, with_sub=True):
        ov = Image.new("RGBA", (W, H), (0, 0, 0, 0))
        if base_logo and glow:
            ov.alpha_composite(scrim, (0, 0))
            lx, ly = (W - base_logo.width) // 2, 22
            g = glow
            if gi != 1.0:
                g = glow.copy(); g.putalpha(g.split()[3].point(lambda p: int(p * gi)))
            ov.alpha_composite(g, (lx, ly)); ov.alpha_composite(g, (lx, ly))   # bloom
            ov.alpha_composite(base_logo, (lx, ly))
        d = ImageDraw.Draw(ov)
        if with_sub:
            # The subtitle sits UNDER THE PICTURE, not down at the footer.
            #
            # It used to be anchored just above the footer, which cost twice.
            # It left a dead slab between the image and the caption — the eye
            # has to travel it on every line — and, worse, it put the caption
            # in the bottom eighth of the frame, which is exactly where
            # Instagram and TikTok lay their OWN interface: the account name,
            # the caption, the audio strip. A subtitle there is a subtitle
            # nobody can read on the platform it was made for.
            #
            # Anchored under the stage, it closes the gap and clears the UI.
            # `sub_y` overrides if a layout genuinely wants it low.
            for sz in (38, 35, 32, 29, 26):
                f = ImageFont.truetype(FEN[lang], sz); lines = wrap(d, text, f, 960)
                if len(lines) <= 3:
                    break
            asc, desc = f.getmetrics(); lh = asc + desc + 6; th = lh * len(lines)
            pad_t, pad_b = 18, 14
            sy = cfg.get("sub_y") or (STAGE_Y + STAGE_H + 46 + pad_t)
            # Never let a three-line caption run into the footer.
            sy = min(sy, 1772 - 16 - pad_b - th)
            d.rounded_rectangle([70, sy - pad_t, W - 70, sy + th + pad_b], 24, fill=(6, 9, 14, 200))
            y = sy
            for ln in lines:
                tw = d.textlength(ln, font=f); d.text(((W - tw) // 2, y), ln, font=f, fill=WHITE); y += lh
        # footer (contact + address), always on
        d.rectangle([0, 1772, W, H], fill=(8, 11, 17, 255)); d.rectangle([0, 1772, W, 1776], fill=ACC)
        # footer font: prefer the Latin/en face (contact + address are usually Latin),
        # but fall back to this build's own font so a config WITHOUT an "en" language
        # (e.g. a Hindi-only cut) still renders instead of raising KeyError.
        foot_font = FEN.get("en") or FEN[lang]
        # Shrink-to-fit: a long contact/address line used to overflow 1080px. Because
        # the x origin is (W - text_width) // 2, an over-wide string yields a NEGATIVE
        # x and gets clipped at BOTH edges. Step the size down until it fits.
        def _fit(text, start_size, min_size, margin=80):
            size = start_size
            f = ImageFont.truetype(foot_font, size)
            w = d.textlength(text, font=f)
            while w > (W - margin) and size > min_size:
                size -= 1
                f = ImageFont.truetype(foot_font, size)
                w = d.textlength(text, font=f)
            return f, w

        c1 = cfg["company"]["contact_line"]
        f1, w1 = _fit(c1, 44, 24)
        d.text(((W - w1) // 2, 1806), c1, font=f1, fill=ACC)
        addr = cfg["company"].get("address", "")
        if addr:
            f2, w2 = _fit(addr, 30, 16)
            d.text(((W - w2) // 2, 1862), addr, font=f2, fill=GREY)
        ov.save(path)

    logo_key = _file_key(cfg["company"].get("logo") or "")

    def video(lang, sd):
        clips = []
        for i, sc in enumerate(cfg["scenes"]):
            gi = 0.55 + 0.45 * abs(math.sin(i * 0.9))          # logo shimmer across scenes
            disp = (sc.get("sub") or {}).get(lang) or sc["vo"][lang]   # caption may differ from VO
            imgs = scene_images(sc)
            img_keys = "|".join(_file_key(os.path.join(cfg["images_dir"], p)) for p in imgs)
            clip_key = _content_key("clip2", lang, disp, f"{sd[i]:.3f}", img_keys, logo_key,
                                    cfg["languages"][lang], cfg["company"].get("contact_line"),
                                    cfg["company"].get("address"), cfg["maxzoom"], cfg["fps"])
            out = f"{cfg['tmp_dir']}/clip_{lang}_{i}_{clip_key}.mp4"
            if os.path.exists(out) and os.path.getsize(out) > 10000:
                print(f"  clip {lang}{i}: cached", flush=True)
                clips.append(out); continue
            ovp = f"{cfg['tmp_dir']}/ov_{lang}_{i}.png"; overlay(disp, lang, gi, ovp)

            # A still may not hold longer than `max_hold`.
            #
            # This is the single change that stops a reel reading as a
            # slideshow. A scene is as long as its line takes to say — often
            # six or eight seconds — and parking one frame there for the whole
            # time means the viewer finished looking at it in two and is now
            # waiting. Where the scene has several images it already cuts
            # between them; where it has one, the SAME still is re-staged as
            # two or three shots with different moves, which gives the cut
            # without needing another asset.
            shots = list(stage[i])
            hold = cfg.get("max_hold", 2.6)
            if len(shots) == 1 and hold > 0 and sd[i] > hold * 1.35:
                shots = shots * max(2, min(4, int(round(sd[i] / hold))))

            total_frames = max(len(shots), round(sd[i] * FPS))
            base_f, extra = divmod(total_frames, len(shots))
            parts = []
            for j, sp in enumerate(shots):
                fj = base_f + (1 if j < extra else 0)
                pdur = fj / FPS
                rate = (MZ - 1) / fj
                z = (f"min(1.0+{rate:.6f}*on,{MZ})" if (i + j) % 2 == 0
                     else f"max({MZ}-{rate:.6f}*on,1.0)")       # alternate in / out
                # A different drift per shot, walked round the compass so
                # consecutive moves never repeat — see PANS.
                pan = PANS[(i * 2 + j) % len(PANS)]
                pout = out if len(shots) == 1 else f"{cfg['tmp_dir']}/part_{lang}_{i}p{j}_{clip_key}.mp4"
                fc = _kenburns_fc(cfg, pdur, z, STAGE_W, STAGE_H, STAGE_X, STAGE_Y, W, H, FPS, pan)
                subprocess.run(["ffmpeg", "-y", "-loop", "1", "-t", f"{pdur:.4f}", "-i", sp,
                                "-loop", "1", "-t", f"{pdur:.4f}", "-i", ovp, "-filter_complex", fc,
                                "-map", "[out]", "-r", str(FPS), "-pix_fmt", "yuv420p", "-c:v", "libx264",
                                "-preset", "veryfast", "-crf", "20", pout], check=True, capture_output=True)
                parts.append(pout)
            if len(parts) > 1:
                lst = f"{cfg['tmp_dir']}/cc_{lang}_{i}.txt"
                with open(lst, "w") as f:
                    for p in parts:
                        f.write(f"file '{os.path.abspath(p)}'\n")
                subprocess.run(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", lst,
                                "-c", "copy", out], check=True, capture_output=True)
            clips.append(out)
        inp = []
        for c in clips:
            inp += ["-i", c]
        fcs, acc, last = [], sd[0], "0:v"
        for i in range(1, N):
            tn, td = transition(i, N, cfg)
            fcs.append(f"[{last}][{i}:v]xfade=transition={tn}:duration={td}:offset={acc - td:.3f}[v{i}]")
            acc += sd[i] - td; last = f"v{i}"
        vid = f"{cfg['tmp_dir']}/video_{lang}.mp4"
        subprocess.run(["ffmpeg", "-y"] + inp + ["-filter_complex", ";".join(fcs), "-map", f"[{last}]",
                        "-r", str(FPS), "-pix_fmt", "yuv420p", "-c:v", "libx264", "-preset", "medium",
                        "-crf", "20", "-movflags", "+faststart", vid], check=True, capture_output=True)
        return vid

    def mux(lang, vid, starts, total):
        inp = []
        for i in range(N):
            inp += ["-i", cfg["_wav"][lang][i]]
        parts = [f"[{i}:a]adelay={int(starts[i] * 1000)}|{int(starts[i] * 1000)}[a{i}]" for i in range(N)]
        vo_norm = f",loudnorm=I={cfg['vo_loudnorm_i']}:TP=-1.5:LRA=11" if cfg.get("vo_loudnorm_i") is not None else ""
        vof = (";".join(parts) + ";" + "".join(f"[a{i}]" for i in range(N)) +
               f"amix=inputs={N}:normalize=0:duration=longest,apad,atrim=0:{total}{vo_norm}[vo]")
        vowav = f"{cfg['tmp_dir']}/vo_{lang}.wav"
        subprocess.run(["ffmpeg", "-y"] + inp + ["-filter_complex", vof, "-map", "[vo]", vowav],
                       check=True, capture_output=True)
        out = os.path.join(cfg["out_dir"], f"{cfg['out_prefix']}-{lang}.mp4")
        # music ducked under VO; strength is config-driven (duck_* / music_volume), defaults
        # unchanged from the original "gentle" values so existing projects keep their old mix
        fc = (f"[2:a]atrim=0:{total},volume={cfg['music_volume']}[mus];[1:a]asplit=2[v1][v2];"
              f"[mus][v1]sidechaincompress=threshold={cfg['duck_threshold']}:ratio={cfg['duck_ratio']}:"
              f"attack={cfg['duck_attack']}:release={cfg['duck_release']}[md];"
              f"[md][v2]amix=inputs=2:normalize=0:duration=first,"
              f"afade=t=out:st={total - 0.5:.3f}:d=0.5[aout]")
        # BUGFIX (unconditional, found while verifying this reel): "-shortest" here was
        # truncating the output by up to ~1s versus the intended `total` — measured on a
        # real build: schedule total=71.14s, but the "-shortest" output measured 70.14s,
        # eating nearly the entire last_tail cushion this file's own docstring promises
        # ("The final scene gets an explicit tail so the closing line is never cut off").
        # Root cause: the filtered [aout] audio's reported length is a little unpredictable
        # (sidechaincompress/amix buffering), and "-shortest" trusts whichever stream LOOKS
        # shortest rather than the timeline this builder actually computed. An explicit
        # "-t total" instead reliably keeps the full video length (audio, which is just
        # silence/fading music by then anyway, ending a fraction of a second early is
        # inaudible — unlike losing most of a second of the CLOSING LINE's cushion).
        subprocess.run(["ffmpeg", "-y", "-i", vid, "-i", vowav, "-i", cfg["_music"], "-filter_complex", fc,
                        "-map", "0:v", "-map", "[aout]", "-c:v", "copy", "-c:a", "aac", "-b:a", "192k",
                        "-t", f"{total:.3f}", "-movflags", "+faststart", out], check=True, capture_output=True)
        print("WROTE", out, f"({total:.1f}s)", flush=True)

    def master(bl):
        # ONE shared-timeline video (per-scene MAX over languages) carrying every
        # language's audio + soft subtitles as selectable tracks. NOTE: Instagram
        # ignores extra tracks; this MKV is a master for archive / YouTube / VLC.
        vlen = [max(dur[l][i] for l in bl) for i in range(N)]
        sd, starts, total = _schedule(cfg, N, vlen)
        # clean clips: logo + footer, NO burned subtitle (subs ride as soft tracks)
        clips = []
        for i in range(N):
            gi = 0.55 + 0.45 * abs(math.sin(i * 0.9))
            ovp = f"{cfg['tmp_dir']}/ovm_{i}.png"; overlay("", bl[0], gi, ovp, with_sub=False)
            out = f"{cfg['tmp_dir']}/clipm_{i}.mp4"
            # `stage[i]` is a LIST of shots — always, even for a scene with one
            # image, since multi-shot re-staging landed. This loop used to hand
            # that list straight to ffmpeg as a path, so the master raised
            # TypeError for EVERY config and the MKV was never written; the
            # caller's try/except turned a total failure into one warning line.
            # It now cuts the scene exactly the way the per-language path does,
            # or the master would be a different edit of the same reel.
            shots = list(stage[i])
            hold = cfg.get("max_hold", 2.6)
            if len(shots) == 1 and hold > 0 and sd[i] > hold * 1.35:
                shots = shots * max(2, min(4, int(round(sd[i] / hold))))
            total_frames = max(len(shots), round(sd[i] * FPS))
            base_f, extra = divmod(total_frames, len(shots))
            parts = []
            for j, sp in enumerate(shots):
                fj = base_f + (1 if j < extra else 0)
                pdur = fj / FPS
                rate = (MZ - 1) / fj
                z = (f"min(1.0+{rate:.6f}*on,{MZ})" if (i + j) % 2 == 0
                     else f"max({MZ}-{rate:.6f}*on,1.0)")
                pan = PANS[(i * 2 + j) % len(PANS)]
                pout = out if len(shots) == 1 else f"{cfg['tmp_dir']}/partm_{i}p{j}.mp4"
                fc = _kenburns_fc(cfg, pdur, z, STAGE_W, STAGE_H, STAGE_X, STAGE_Y, W, H, FPS, pan)
                subprocess.run(["ffmpeg", "-y", "-loop", "1", "-t", f"{pdur:.4f}", "-i", sp,
                                "-loop", "1", "-t", f"{pdur:.4f}", "-i", ovp, "-filter_complex", fc,
                                "-map", "[out]", "-r", str(FPS), "-pix_fmt", "yuv420p", "-c:v", "libx264",
                                "-preset", "veryfast", "-crf", "20", pout], check=True, capture_output=True)
                parts.append(pout)
            if len(parts) > 1:
                lst = f"{cfg['tmp_dir']}/ccm_{i}.txt"
                with open(lst, "w") as f:
                    for pth in parts:
                        f.write(f"file '{os.path.abspath(pth)}'\n")
                subprocess.run(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", lst,
                                "-c", "copy", out], check=True, capture_output=True)
            clips.append(out)
        inp = []
        for c in clips:
            inp += ["-i", c]
        fcs, acc2, last = [], sd[0], "0:v"
        for i in range(1, N):
            tn, td = transition(i, N, cfg)
            fcs.append(f"[{last}][{i}:v]xfade=transition={tn}:duration={td}:offset={acc2 - td:.3f}[v{i}]")
            acc2 += sd[i] - td; last = f"v{i}"
        cleanvid = f"{cfg['tmp_dir']}/video_master.mp4"
        subprocess.run(["ffmpeg", "-y"] + inp + ["-filter_complex", ";".join(fcs), "-map", f"[{last}]",
                        "-r", str(FPS), "-pix_fmt", "yuv420p", "-c:v", "libx264", "-preset", "medium",
                        "-crf", "20", cleanvid], check=True, capture_output=True)
        # one ducked audio track (VO + music) per language on the shared timeline
        auds = []
        for lang in bl:
            ina = []
            for i in range(N):
                ina += ["-i", cfg["_wav"][lang][i]]
            parts = [f"[{i}:a]adelay={int(starts[i] * 1000)}|{int(starts[i] * 1000)}[a{i}]" for i in range(N)]
            vo_norm = f",loudnorm=I={cfg['vo_loudnorm_i']}:TP=-1.5:LRA=11" if cfg.get("vo_loudnorm_i") is not None else ""
            vof = (";".join(parts) + ";" + "".join(f"[a{i}]" for i in range(N)) +
                   f"amix=inputs={N}:normalize=0:duration=longest,apad,atrim=0:{total}{vo_norm}[vo]")
            vowav = f"{cfg['tmp_dir']}/vom_{lang}.wav"
            subprocess.run(["ffmpeg", "-y"] + ina + ["-filter_complex", vof, "-map", "[vo]", vowav],
                           check=True, capture_output=True)
            aud = f"{cfg['tmp_dir']}/audm_{lang}.m4a"
            fc = (f"[1:a]atrim=0:{total},volume={cfg['music_volume']}[mus];[0:a]asplit=2[v1][v2];"
                  f"[mus][v1]sidechaincompress=threshold={cfg['duck_threshold']}:ratio={cfg['duck_ratio']}:"
                  f"attack={cfg['duck_attack']}:release={cfg['duck_release']}[md];"
                  f"[md][v2]amix=inputs=2:normalize=0:duration=first,afade=t=out:st={total - 0.5:.3f}:d=0.5[aout]")
            subprocess.run(["ffmpeg", "-y", "-i", vowav, "-i", cfg["_music"], "-filter_complex", fc,
                            "-map", "[aout]", "-c:a", "aac", "-b:a", "192k", aud], check=True, capture_output=True)
            auds.append(aud)
        # soft subtitle (SRT) per language
        srts = []
        for lang in bl:
            blocks = []
            for i in range(N):
                st = starts[i]; en = st + dur[lang][i]
                disp = (cfg["scenes"][i].get("sub") or {}).get(lang) or cfg["scenes"][i]["vo"][lang]
                blocks.append(f"{i + 1}\n{_srt_t(st)} --> {_srt_t(en)}\n{disp}\n")
            srt = f"{cfg['tmp_dir']}/sub_{lang}.srt"
            with open(srt, "w") as fh:
                fh.write("\n".join(blocks))
            srts.append(srt)
        # mux MKV: clean video + N audio tracks + N subtitle tracks, language-tagged
        out = os.path.join(cfg["out_dir"], f"{cfg['out_prefix']}-multiaudio.mkv")
        cmd = ["ffmpeg", "-y", "-i", cleanvid]
        for a in auds:
            cmd += ["-i", a]
        for s in srts:
            cmd += ["-i", s]
        cmd += ["-map", "0:v"]
        for k in range(len(auds)):
            cmd += ["-map", f"{k + 1}:a"]
        for k in range(len(srts)):
            cmd += ["-map", f"{1 + len(auds) + k}:s"]
        cmd += ["-c:v", "copy", "-c:a", "copy", "-c:s", "srt"]
        iso = {"en": "eng", "hi": "hin"}
        for k, lang in enumerate(bl):
            cmd += [f"-metadata:s:a:{k}", f"language={iso.get(lang, lang)}", f"-metadata:s:a:{k}", f"title={lang.upper()} voice"]
            cmd += [f"-metadata:s:s:{k}", f"language={iso.get(lang, lang)}"]
        cmd += ["-disposition:a:0", "default", out]
        subprocess.run(cmd, check=True, capture_output=True)
        print("WROTE", out, f"({total:.1f}s · {len(auds)} audio + {len(srts)} sub tracks)", flush=True)

    blangs = cfg.get("_build_langs") or list(FEN)
    if not blangs:
        print("!! no language has complete TTS — nothing to build", flush=True); return
    tim = {l: timings(l) for l in blangs}
    cfg["_music"] = make_music(cfg, max(t[2] for t in tim.values()) + 2)
    for lang in blangs:
        sd, starts, total = tim[lang]
        print(f"[{lang}] scenes={sd} total={total}s", flush=True)
        mux(lang, video(lang, sd), starts, total)
    if cfg.get("multi_audio") and len(blangs) >= 2:
        try:
            master(blangs)
        except Exception as e:
            print("!! multi-audio master failed (single-language reels are fine):", repr(e), flush=True)


def main():
    cfg = load_cfg(sys.argv[1] if len(sys.argv) > 1 else "config.json")
    print("== TTS ==", flush=True)
    dur = gen_tts(cfg)
    print("== build ==", flush=True)
    build(cfg, dur)
    print("DONE", flush=True)


if __name__ == "__main__":
    main()
